# Generated by Django 3.2.25 on 2024-08-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partition_appData_migrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_file', models.FileField(upload_to='models/')),
                ('appariel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appariel')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
