# Generated by Django 3.2.25 on 2024-08-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240806_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appariel',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='appariel',
            old_name='nom',
            new_name='name',
        ),
    ]
