# Generated by Django 3.2.25 on 2024-08-09 15:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_mlmodels_mlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(upload_to=core.models.ml_model_upload_path),
        ),
    ]
